# general settings
name: LapH_IV
model_type: LapH_Model
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: IV_Fusion
    type: FusionImageDataset
    dataroot_vi: datasets/50_TNO/128_vis.lmdb
    dataroot_ir: datasets/50_TNO/128_ir.lmdb
    filename_tmpl: '{}'
    io_backend:
       type: lmdb

    if_fix_size: true # training will be slower if the data shape not fixed (both num_gpu and batch_size need to be 1)
    gt_size: 128 # training size

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 16
    batch_size_per_gpu: 32
    dataset_enlarge_ratio: 1
    prefetch_mode: cuda
    pin_memory: true

  val:
    name: IV_Fusion
    type: FusionImageDataset
    dataroot_vi: datasets/221_Road/test_221_vis.lmdb
    dataroot_ir: datasets/221_Road/test_221_inf.lmdb
    io_backend:
      type: lmdb

# network structures
network_g:
  type: LapH
  hf_dim: 16
  lf_dim: 32
  num_high: 3


# path
path:
  pretrain_network_g: ~
  strict_load_g: false
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]
  scheduler:
    type: MultiStepLR
    milestones: [8100]
    gamma: 0.5

  total_iter: 8100
  total_epoch: 7
  warmup_iter: -1  # no warm up

  # losses
  ssim_opt:
    type: SSIM
    loss_weight: 1
  gradient_opt:
    type: GradientLoss
    loss_weight: 10
  contrast_opt:
    type: ContrastLoss
    loss_weight: 0.5

# validation settings
val:
  val_freq: !!float 3e2
  save_img: true
  stride: 96
  crop_size: 128

  metrics:
    ei:
      type: calculate_ei
      crop_border: 0
      test_y_channel: True
    sf:
      type: calculate_sf
      crop_border: 0
      test_y_channel: True
    ssim:
      type: calculate_fusion_ssim
      crop_border: 0
      test_y_channel: True

# logging settings
logger:
  print_freq: 10
  save_checkpoint_freq: !!float 3e2
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500